name: Push Docker Image To AWS ECR Using OIDC

on:
  push:
    branches:
      - dev
      - uat
    paths:
      - 'Week2/aws-ecr-pipeline/**'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: learndevopsnow
  AWS_ACCOUNT_ID: 936286918918 # Replace Your ASW ACCOUNT ID
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Week2/aws-ecr-pipeline

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug OIDC claims
        run: |
          TOKEN_JSON=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com")
          ID_TOKEN=$(echo "$TOKEN_JSON" | jq -r .value)
          echo "$ID_TOKEN" | awk -F. '{print $2}' | base64 -d 2>/dev/null | jq -r

      - name: Configure AWS Credentials Using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::936286918918:role/github-actions-ecr-role
          aws-region: us-east-2

      - name: Login To Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build And Push Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --push \
            -f Dockerfile \
            -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${IMAGE_TAG::7} \
            .

      - name: Dummy ECS Deploy Stage
        run: |
          echo "ECS deploy dummy stage only"
          echo "Target Stage: ${{ steps.stage.outputs.target_stage }}"
          echo "Image URI: ${{ steps.image.outputs.image_uri }}"
          echo "Later ECS lesson will add"
          echo "aws ecs register-task-definition"
          echo "aws ecs update-service"
