name: Push Docker Image To AWS ECR Using Access Key

on:
  push:
    branches:
      - main
    paths:
      - 'Week2/aws-ecr-pipeline/**'

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: learndevopsnow
  AWS_ACCOUNT_ID: 637423240100 # Replace Your ASW ACCOUNT ID
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Week2/aws-ecr-pipeline

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials Using Access Key
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login To Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build And Push Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --push \
            -f Dockerfile \
            -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${IMAGE_TAG::7} \
            .